version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: chmod a+x ./deploy.sh
      - run: ./deploy.sh
    branches:
      only:
        - master
