baseURL = "http://itsadougs.life"
languageCode = "en-us"
title = "it's a dougs life"
theme = "kiss"

[params.info]
enableSocial = true


[params.social]
twitter = "d0ugs"
email = "e@dou.gs"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["twitter","email"]

[taxonomies]
tag ="tags"


[params.assets]
customCSS = ["css/custom.css"]
